project:
  type: website

website:
  title: "fur-cp-ds"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Data Analysis
      - href: sources.qmd
        text: Sources
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# site outline:
# home - general playlist info, surface level video stats
# data analysis - popular cover srcs, chip usage
# sources - the sause
# about - about

